# Generated by Django 4.0.1 on 2022-03-20 20:35

from django.db import migrations


def populate_db(apps, schema_editor):
    Unit = apps.get_model('unitconv', 'Unit')

class Migration(migrations.Migration):

    dependencies = [
        ('unitconv', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_db),
    ]
